### PR TITLE
Fix #1 - Improve messages logged in Loggly

### LINKED ISSUE #1: Improve messages logged in Loggly
It seems that when an email fails to be sent (because there is no recipients for example), the only message we see in Loggly is:

```
2015-06-16 20:10:36.000 UTC [techMail.js] {}
```

Improving these messages could have helped to detect https://github.com/AirVantage/av-accounts/issues/39 sooner.

### PR DESCRIPTION
**Pull request by jlescot**
Add more context in logged messages to better understand what is really happening...

### CODE REVIEW

File: techMail.js [hunk 1]
```diff
@@ -34,11 +34,11 @@ module.exports = function(configuration, templatesDir) {
 
             emailTemplates(templatesDir, function(err, template) {
                 if (err) {
-                    logger.error(err);
+                    logger.error("Unable to configure the template engine... - Details:", err && err.stack || err);
```
Comment (phtrivier) [inline techMail.js:37]: Not sure I get it... The bug says that the message was `{}`. Is there some cases where we have an error, and cases where we don't ?

Comment (jlescot) [inline techMail.js:37]: I think that the `{}` message was logged in the last step `transporter.sendMail(...` because the list of recipients was empty. But yes, it means that in some case, the `err` is an empty object, so I am just trying to add more context to better identify further issues we could encounter.

Since I did not find useful information about the `err` object in the case of the `email-templates` module, I am logging as much as I can

File: techMail.js [hunk 2]
```diff
@@ -34,11 +34,11 @@ module.exports = function(configuration, templatesDir) {
...
                 } else {
                     template(options.template, locals, function(err, html, text) {
                         if (err) {
-                            logger.error(err);
+                            logger.error("Unable to render the template '" + options.template + "' - Details:", err && err.stack || err);
```
Comment (phtrivier) [inline techMail.js:41]: should we check options.template is defined here (before doing a "+") ? Or calling logger.error with multiple arguments (I think it should work...)

**Comment by phtrivier** [comment]
Will I need any specific configuration to test this ? What's the easiest way to reproduce sending an email ?

File: techMail.js (hunk 2 above)
Comment (jlescot) [inline techMail.js:41]: It should be the same using either '+' or ',' to build the error message, in the case `options.template` is null or undefined or an empty String

**Comment by jlescot** [comment]
I will try to make more tests locally, mostly in order to simulate that a template is missing or malformed. On your side, in order to test the nominal case, you should be able to do a Signup in accounts and check that you got the notification in the console that an email was sent (leave the property `stub_transport: true` in order to not really send a mail using SendGrid)

**Comment by phtrivier** [comment]
Code looks good to me.
